"""Added content field to Lesson model

Revision ID: 44ee2d7459ef
Revises: 7e3d9fcbc6e8
Create Date: 2024-11-03 19:10:44.820864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ee2d7459ef'
down_revision = '7e3d9fcbc6e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False, server_default='Default Content'))
        batch_op.alter_column('lesson_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('assigned_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
