"""empty message

Revision ID: 4a02fa7d67e2
Revises: 9a77e86a1fb6
Create Date: 2024-11-03 16:28:29.691254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a02fa7d67e2'
down_revision = '9a77e86a1fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.alter_column('lesson_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('assigned_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.alter_column('assigned_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('lesson_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
