"""Updated Student and Subject relationships to remove redundancy

Revision ID: 5f8685834c6b
Revises: 955524f46354
Create Date: 2024-11-02 22:46:22.438773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f8685834c6b'
down_revision = '955524f46354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('temporary_column')

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint('subject_student_id_fkey', type_='foreignkey')
        batch_op.drop_column('score')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('subject_student_id_fkey', 'student', ['student_id'], ['id'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporary_column', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
