"""Add Lesson model and updates

Revision ID: 83d2db4da74b
Revises: c8c5861c62e9
Create Date: 2024-10-29 22:20:30.118401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d2db4da74b'
down_revision = 'c8c5861c62e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_level', sa.Integer(), nullable=False),
    sa.Column('engagement_activity', sa.Text(), nullable=False),
    sa.Column('learning_intention', sa.Text(), nullable=False),
    sa.Column('success_criteria', sa.Text(), nullable=False),
    sa.Column('vocabulary', sa.Text(), nullable=True),
    sa.Column('explicit_teaching', sa.Text(), nullable=False),
    sa.Column('examples', sa.Text(), nullable=True),
    sa.Column('tasks', sa.Text(), nullable=False),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('engagement_rating', sa.Integer(), nullable=True),
    sa.Column('reflection_feedback', sa.Text(), nullable=True),
    sa.Column('task_completion_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    op.drop_table('student_progress')
    op.drop_table('lesson')
    # ### end Alembic commands ###
