"""Updated student model after downgrade and upgrade

Revision ID: 955524f46354
Revises: acaccf52bb7d
Create Date: 2024-11-02 20:37:44.374832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955524f46354'
down_revision = 'acaccf52bb7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporary_column', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('temporary_column')

    # ### end Alembic commands ###
