"""Add role column to Teacher model with nullable option initially

Revision ID: 9a77e86a1fb6
Revises: 300df5f0c826
Create Date: 2024-11-03 15:52:55.311968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a77e86a1fb6'
down_revision = '300df5f0c826'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Creating new tables
    op.create_table('core_curriculum_module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('year_level', sa.Integer(), nullable=False),
    sa.Column('module_content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extended_pathway',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('difficulty_level', sa.String(length=50), nullable=False),
    sa.Column('module_content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_skill_band',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('skill_band', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Altering existing tables
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_type', sa.String(length=50), nullable=True))  # Allowing NULLs initially
        batch_op.add_column(sa.Column('assigned_by', sa.String(length=100), nullable=True))  # Allow NULLs initially
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'teacher', ['owner_id'], ['id'])
        batch_op.drop_column('examples')

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))  # Initially allow NULL

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('lesson_type')
        batch_op.add_column(sa.Column('examples', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('owner_id')
        batch_op.drop_column('assigned_by')
        batch_op.drop_column('lesson_type')

    op.drop_table('student_skill_band')
    op.drop_table('extended_pathway')
    op.drop_table('core_curriculum_module')
    # ### end Alembic commands ###

