"""Added new fields to Lesson model

Revision ID: acaccf52bb7d
Revises: c2c0c8b769ac
Create Date: 2024-10-30 21:39:15.475625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acaccf52bb7d'
down_revision = 'c2c0c8b769ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        # Add columns with default values to handle existing rows
        batch_op.add_column(sa.Column('subject', sa.String(length=100), nullable=False, server_default="General"))
        batch_op.add_column(sa.Column('content_type', sa.String(length=50), nullable=False, server_default="Text"))
        batch_op.add_column(sa.Column('complexity_level', sa.String(length=50), nullable=False, server_default="Beginner"))
        batch_op.add_column(sa.Column('engagement_level', sa.String(length=50), nullable=True, server_default="1"))

    # Remove server defaults once data is populated
    op.alter_column('lesson', 'subject', server_default=None)
    op.alter_column('lesson', 'content_type', server_default=None)
    op.alter_column('lesson', 'complexity_level', server_default=None)
    op.alter_column('lesson', 'engagement_level', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('engagement_level')
        batch_op.drop_column('complexity_level')
        batch_op.drop_column('content_type')
        batch_op.drop_column('subject')
    # ### end Alembic commands ###
